/**
 * Detector confidence thresholds (calibrated post-validation)
 *
 * Format: { detector: { flag_threshold, warn_threshold } }
 * Thresholds calibrated against:
 *   - 3 real May 2026 attack campaigns (validation)
 *   - Top 1,000 npm packages (false positive calibration)
 */

export default {
  'TIER1-VERSION-ANOMALY': {
    flag_threshold: 72,
    warn_threshold: 60,
    notes:
      'Sentinel patterns (99.99.99/11.11.11/10.10.10) always flag at 92 regardless of threshold',
  },
  'TIER1-OBFUSCATION-HEURISTICS': {
    flag_threshold: 75,
    warn_threshold: 60,
    notes: 'Increased from 70 post-FP analysis; bundlers (webpack, terser) exempt via whitelist',
  },
  'TIER1-BINARY-EMBED': {
    flag_threshold: 80,
    warn_threshold: 65,
    notes:
      'High threshold justified; platform-specific binary sets are rare in legitimate packages',
  },
  'TIER1-LIFECYCLE-HOOK': {
    flag_threshold: 65,
    warn_threshold: 50,
    notes: 'Moderate threshold; lifecycle hooks common but uncommon in top 1K packages',
  },
  'TIER1-INFOSTEALER': {
    flag_threshold: 72,
    warn_threshold: 55,
    notes: 'Pattern-based; calibrated for C2 signatures, credential exfil patterns',
  },
  'TIER1-TYPOSQUAT': {
    flag_threshold: 85,
    warn_threshold: 70,
    notes:
      'Calibrated to 85 post-FP analysis on top 1,000 packages; 46 edit-distance=1 FPs eliminated at this threshold',
  },
  'TIER1-METADATA-SPOOF': {
    flag_threshold: 70,
    warn_threshold: 55,
    notes: 'Namespace/repo URL spoofing; moderate threshold for legitimate clones',
  },
  'TIER1-VERSION-CONFUSION': {
    flag_threshold: 75,
    warn_threshold: 60,
    notes: 'High-version heuristics (major >= 9); tuned to avoid FP on pre-release tags',
  },
  'TIER1-CLOUD-IMDS': {
    flag_threshold: 80,
    warn_threshold: 65,
    notes: 'IMDS endpoint targeting is rarely legitimate; high threshold',
  },
  'TIER1-MULTISTAGE-POSTINSTALL': {
    flag_threshold: 75,
    warn_threshold: 60,
    notes: 'Two-stage download+exec patterns; moderate threshold',
  },
  'TIER1-SLSA-ATTESTATION': {
    flag_threshold: 85,
    warn_threshold: 70,
    notes: 'Placeholder; threshold TBD when API stabilizes',
  },
  'TIER1-SELF-PROPAGATION': {
    flag_threshold: 75,
    warn_threshold: 60,
    burst_window_minutes: 60,
    min_packages_burst: 3,
    identical_payload_weight: 40,
    notes: 'D10: Detects burst republish patterns (Miasma campaign)',
  },
  'TIER1-ENCRYPTED-C2': {
    flag_threshold: 70,
    warn_threshold: 50,
    known_c2_endpoints: [
      'filev2.getsession.org',
      'api.signal.org',
      '*.briarproject.org',
      'api.ricochet.im',
    ],
    onion_pattern_weight: 30,
    encoded_url_weight: 35,
    env_var_c2_weight: 40,
    notes: 'D11: Detects Session/Oxen, Signal, Briar, Tor C2 channels',
  },
  'TIER1-TRANSITIVE-DEPS': {
    flag_threshold: 80,
    warn_threshold: 50,
    new_package_days: 7,
    unknown_depth_weight: 45,
    typosquat_depth_weight: 50,
    different_maintainer_weight: 35,
    notes: 'D12: Deep dependency tree analysis for injection attacks',
  },
  'TIER1-MAINTAINER-COMPROMISE': {
    flag_threshold: 75,
    warn_threshold: 60,
    velocity_burst_multiplier: 5,
    burst_window_hours: 24,
    min_velocity_baseline: 0.5,
    duplicate_version_weight: 40,
    unusual_timing_weight: 25,
    cross_package_burst_weight: 50,
    notes: 'D13: Version velocity anomaly and maintainer compromise detection',
  },
  'D15-MEMORY-EXTRACTION': {
    flag_threshold: 75,
    warn_threshold: 55,
    pattern_weights: {
      oidc_token_access: 60,
      memory_introspection: 55,
    },
    pattern_confidence: {
      oidc_token_access: 0.95,
      memory_introspection: 0.9,
    },
    notes: 'D15: Memory Credential Extraction (Miasma Escalated)',
  },
  'D16-EBPF-ROOTKIT': {
    flag_threshold: 100,
    warn_threshold: 70,
    pattern_weights: {
      ebpf_bytecode: 70,
      bpf_syscall: 65,
      kernel_hook: 70,
      syscall_hook: 75,
      hiding_intent: 50,
      kernel_ffi: 50,
    },
    pattern_confidence: {
      ebpf_bytecode: 0.95,
      bpf_syscall: 0.9,
      kernel_hook: 0.95,
      syscall_hook: 0.98,
      hiding_intent: 0.8,
      kernel_ffi: 0.8,
    },
    notes: 'D16: eBPF Rootkit Detection (IronWorm)',
  },
  'D17-PRIVILEGE-ESCALATION': {
    flag_threshold: 120,
    warn_threshold: 70,
    pattern_weights: {
      capability_request: 70,
      exploit_reference: 20,
      setuid_attempt: 65,
      sudo_bypass: 75,
      kernel_memory_access: 70,
      kernel_module_load: 80,
    },
    pattern_confidence: {
      capability_request: 0.95,
      exploit_reference: 0.9,
      setuid_attempt: 0.95,
      sudo_bypass: 0.98,
      kernel_memory_access: 0.95,
      kernel_module_load: 0.98,
    },
    notes: 'D17: Privilege Escalation Patterns (Miasma + IronWorm)',
  },
  'D14-BUILD-CONFIG-ABUSE': {
    flag_threshold: 70,
    warn_threshold: 50,
    pattern_weights: {
      shell_exec: 50,
      process_spawn: 45,
      env_access: 35,
      fs_access: 40,
      http_request: 50,
      path_traversal: 55,
      hardcoded_key: 60,
      getenv_call: 35,
      curl_call: 45,
      execve_call: 55,
      credential_scan: 50,
      socket_call: 40,
      environ_access: 35,
    },
    legitimate_native_addons: [
      'node-sass',
      'sqlite3',
      'bcrypt',
      '@mapbox/node-pre-gyp',
      'better-sqlite3',
      'sharp',
      'canvas',
      'node-gyp',
      'prebuild-install',
    ],
    pattern_confidence: {
      hardcoded_key: 0.95,
      execve_call: 0.9,
      socket_call: 0.75,
      env_access: 0.6,
      getenv_call: 0.7,
      curl_call: 0.85,
    },
    max_binary_size_bytes: 10 * 1024 * 1024,
    binary_size_weight: 30,
    binary_age_mismatch_days: 30,
    undeclared_gyp_weight: 45,
    known_reputable_packages: [
      'electron',
      'puppeteer',
      'playwright',
      'sharp',
      'esbuild',
      'node-gyp',
      '@mapbox/node-pre-gyp',
      'node-pre-gyp',
      'webpack',
      'vite',
      'rollup',
    ],
    notes: 'D14: Build Configuration Abuse (Phantom Gyp / Miasma variant)',
  },
  'D18-SELF-DEFENDING': {
    flag_threshold: 170,
    warn_threshold: 120,
    pattern_weights: {
      debugger_detection: 30,
      execution_guard: 35,
      package_validation: 8,
      environment_detection: 25,
      anti_tamper: 65,
      file_modification_detection: 20,
    },
    pattern_confidence: {
      debugger_detection: 0.8,
      execution_guard: 0.85,
      anti_tamper: 0.9,
    },
    notes: 'D18: Self-Defending/Environment-Aware Malicious Code; file_mod_detection weight 20',
  },
  'D19-MODULE-LOAD': {
    flag_threshold: 160,
    warn_threshold: 120,
    pattern_weights: {
      iife_pattern: 35,
      toplevel_await: 45,
      module_hook: 40,
      constructor_execution: 50,
    },
    pattern_confidence: {
      iife_pattern: 0.6,
      toplevel_await: 0.7,
      constructor_execution: 0.85,
    },
    notes: 'D19: Module-Load Execution at Install Time',
  },
  'D20-PROFILING-RECON': {
    flag_threshold: 170,
    warn_threshold: 120,
    pattern_weights: {
      platform_enumeration: 20,
      user_enumeration: 25,
      network_check: 25,
      cloud_detection: 45,
      directory_scan: 20,
      tools_detection: 25,
    },
    pattern_confidence: {
      platform_enumeration: 0.6,
      user_enumeration: 0.65,
      cloud_detection: 0.8,
    },
    notes:
      'D20: Profiling & Reconnaissance; weights lowered for platform_enum + user_enum + dir_scan',
  },
  'D21-SELF-CLEANING': {
    flag_threshold: 180,
    warn_threshold: 120,
    pattern_weights: {
      self_deletion: 85,
      package_json_manipulation: 75,
      file_swap: 60,
      log_cache_clear: 45,
      git_history_removal: 70,
      timestamp_manipulation: 50,
    },
    pattern_confidence: {
      self_deletion: 0.99,
      package_json_manipulation: 0.95,
      git_history_removal: 0.95,
    },
    notes: 'D21: Self-Cleaning / Evidence Removal',
  },
  'D22-AI-TOKEN-TARGETING': {
    flag_threshold: 80,
    warn_threshold: 60,
    pattern_weights: {
      claude_token_targeting: 90,
      openai_token_targeting: 90,
      gemini_token_targeting: 85,
      mistral_token_targeting: 85,
      cursor_token_targeting: 85,
      ai_config_targeting: 80,
      ai_token_exfiltration: 95,
      ai_platform_enumeration: 75,
    },
    pattern_confidence: {
      ai_token_exfiltration: 0.99,
      claude_token_targeting: 0.98,
      openai_token_targeting: 0.98,
      ai_config_targeting: 0.98,
      gemini_token_targeting: 0.95,
      mistral_token_targeting: 0.95,
      cursor_token_targeting: 0.95,
      ai_platform_enumeration: 0.9,
    },
    notes: 'D22: AI Token Targeting (IronWorm AI-targeted infostealer patterns)',
  },
  'D23-GITHUB-AUTHOR-SPOOF': {
    flag_threshold: 85,
    warn_threshold: 65,
    pattern_weights: {
      github_author_spoof: 95,
      spoofed_git_commit: 90,
      force_push: 85,
      force_push_lease: 70,
      ai_workflow_impersonation: 80,
      full_author_spoof_attack: 99,
      authenticated_spoof_push: 95,
      repo_hijacking: 85,
    },
    pattern_confidence: {
      full_author_spoof_attack: 0.99,
      authenticated_spoof_push: 0.99,
      github_author_spoof: 0.99,
      spoofed_git_commit: 0.99,
      force_push: 0.95,
      repo_hijacking: 0.9,
      ai_workflow_impersonation: 0.9,
      force_push_lease: 0.85,
    },
    notes: 'D23: GitHub Author Spoof (claude@/gpt@ noreply impersonation, IronWorm)',
  },
};
